In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/content/student_exam_scores.csv")

In [3]:
data

,student_id,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,S001,8.0,8.8,72.1,45,30.2
1,S002,1.3,8.6,60.7,55,25.0
2,S003,4.0,8.2,73.7,86,35.8
3,S004,3.5,4.8,95.1,66,34.0
4,S005,9.1,6.4,89.8,71,40.3
...,...,...,...,...,...,...
195,S196,10.5,5.4,94.0,87,42.7
196,S197,7.1,6.1,85.1,92,40.4
197,S198,1.6,6.9,63.8,76,28.2
198,S199,12.0,7.3,50.5,58,42.0
199,S200,10.2,6.3,97.4,68,37.8

In [4]:
data.head(5)

,student_id,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,S001,8.0,8.8,72.1,45,30.2
1,S002,1.3,8.6,60.7,55,25.0
2,S003,4.0,8.2,73.7,86,35.8
3,S004,3.5,4.8,95.1,66,34.0
4,S005,9.1,6.4,89.8,71,40.3

In [5]:
data.shape

(200, 6)

In [6]:
data.index

RangeIndex(start=0, stop=200, step=1)

In [7]:
data.columns

Index(['student_id', 'hours_studied', 'sleep_hours', 'attendance_percent',
       'previous_scores', 'exam_score'],
      dtype='object')

In [8]:
data.dtypes

student_id             object
hours_studied         float64
sleep_hours           float64
attendance_percent    float64
previous_scores         int64
exam_score            float64
dtype: object

In [9]:
data['sleep_hours'].unique()

array([8.8, 8.6, 8.2, 4.8, 6.4, 5.1, 6. , 4.3, 5.9, 8.9, 5.3, 7.9, 6.3,
       6.1, 9. , 6.8, 7.6, 5.5, 6.9, 6.7, 7.7, 6.5, 8.3, 4.4, 4.9, 7. ,
       7.4, 5.2, 4.6, 8.5, 7.1, 6.6, 8.7, 5. , 5.6, 7.8, 8.4, 5.8, 7.5,
       7.3, 4. , 8.1, 4.7, 4.5, 5.4, 7.2, 8. , 4.1, 5.7, 6.2])

In [10]:
data['sleep_hours'].nunique()

50

In [11]:
data['previous_scores'].unique()

array([45, 55, 86, 66, 71, 75, 88, 84, 70, 81, 85, 68, 90, 41, 58, 54, 65,
       59, 82, 77, 63, 73, 62, 67, 87, 61, 69, 57, 56, 47, 52, 60, 74, 51,
       53, 78, 46, 93, 40, 48, 42, 43, 80, 95, 76, 92, 44, 83, 49, 91, 79,
       89, 64, 50])

In [12]:
data['hours_studied'].nunique()

96

In [13]:
data['exam_score'].unique()

array([30.2, 25. , 35.8, 34. , 40.3, 35.7, 37.9, 18.3, 34.7, 24.7, 29.3,
       35.1, 31.2, 41.1, 34.1, 28.9, 36.3, 35.6, 17.1, 46. , 36.1, 29.6,
       35.9, 39.2, 30. , 29. , 26.5, 37.2, 36.2, 34.5, 41.6, 38.1, 42.7,
       32. , 44.7, 38.3, 39.8, 35. , 34.2, 23.1, 30.3, 26.1, 31.8, 31.6,
       31.1, 41.2, 30.6, 28.8, 30.7, 26.9, 46.4, 34.4, 37. , 35.2, 38.2,
       33. , 29.2, 48.6, 27.1, 39.5, 36.7, 21.7, 32.2, 33.5, 23.9, 20.8,
       47.9, 41.9, 29.5, 26.3, 39.9, 30.8, 32.4, 48.9, 38. , 51.3, 28.6,
       32.1, 27.3, 37.5, 29.1, 28.1, 28.7, 36.9, 36. , 37.1, 31.4, 31.3,
       32.6, 24.1, 23.7, 23.2, 42.2, 39.6, 34.8, 34.6, 26.4, 43.1, 25.2,
       29.8, 40.9, 44.1, 39.3, 21.2, 38.6, 26.8, 32.9, 45.7, 40.8, 29.9,
       43.3, 19. , 45.8, 35.5, 21.9, 42.3, 27.7, 33.4, 29.7, 23.6, 33.6,
       40.6, 30.1, 42. , 22.8, 45.3, 31. , 44.8, 38.4, 19.4, 39.4, 22.9,
       23.4, 28. , 46.7, 33.8, 40.4, 28.2, 37.8])

In [14]:
data.value_counts()

student_id  hours_studied  sleep_hours  attendance_percent  previous_scores  exam_score
S001        8.0            8.8          72.1                45               30.2          1
S002        1.3            8.6          60.7                55               25.0          1
S003        4.0            8.2          73.7                86               35.8          1
S004        3.5            4.8          95.1                66               34.0          1
S005        9.1            6.4          89.8                71               40.3          1
                                                                                          ..
S196        10.5           5.4          94.0                87               42.7          1
S197        7.1            6.1          85.1                92               40.4          1
S198        1.6            6.9          63.8                76               28.2          1
S199        12.0           7.3          50.5                58               42.0          1
S200        10.2           6.3          97.4                68               37.8          1
Name: count, Length: 200, dtype: int64

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          200 non-null    object
 1   hours_studied       200 non-null    float64
 2   sleep_hours         200 non-null    float64
 3   attendance_percent  200 non-null    float64
 4   previous_scores     200 non-null    int64
 5   exam_score          200 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 9.5+ KB

In [16]:
data.head(2)

,student_id,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,S001,8.0,8.8,72.1,45,30.2
1,S002,1.3,8.6,60.7,55,25.0

In [17]:
data['student_id'].nunique()

200

In [18]:
data.hours_studied.value_counts()

hours_studied
3.9     7
3.5     6
10.5    5
3.4     5
9.9     4
       ..
2.3     1
7.3     1
6.1     1
11.8    1
10.2    1
Name: count, Length: 96, dtype: int64

In [21]:
data.head(2)

,student_id,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,S001,8.0,8.8,72.1,45,30.2
1,S002,1.3,8.6,60.7,55,25.0

In [29]:
data.isnull().sum()

student_id            0
hours_studied         0
sleep_hours           0
attendance_percent    0
previous_scores       0
exam_score            0
dtype: int64

In [30]:
data.notnull().sum()

student_id            0
hours_studied         0
sleep_hours           0
attendance_percent    0
previous_scores       0
exam_score            0
dtype: int64

In [40]:
data.exam_score.mean()

nan

In [36]:
data.attendance_percent.median()

nan

In [37]:
data.attendance_percent.mode()

Series([], Name: attendance_percent, dtype: float64)

In [38]:
data.attendance_percent.std()

nan

In [39]:
data['attendance_percent'].var()

nan

In [41]:
data.min()

student_id            NaN
hours_studied         NaN
sleep_hours           NaN
attendance_percent    NaN
previous_scores       NaN
exam_score            NaN
dtype: object

In [42]:
data.max()

student_id            NaN
hours_studied         NaN
sleep_hours           NaN
attendance_percent    NaN
previous_scores       NaN
exam_score            NaN
dtype: object